import { ScoutingConfig } from "../lib/configTypes";

export const config2026: ScoutingConfig = {
  year: 2026,
  name: "FRC 2026",
  matchSections: ["auto", "teleop", "endgame", "notes"],
  pitSections: ["general", "drivetrain", "shooter", "auto", "endgame", "notes"],

  matchFields: [
    // ── AUTO ──────────────────────────────────────────────────────────────────
    {
      id: "auto_start_pos",
      label: "Starting Position",
      type: "select",
      options: ["Left Trench", "Left Bump", "Right Trench", "Right Bump", "Hub"],
      section: "auto",
      aggregatable: false,
    },
    {
      id: "auto_collect_zone",
      label: "Auto Collection Zone",
      type: "multiselect",
      options: ["Neutral Zone", "Depot", "Human Player", "None"],
      section: "auto",
      aggregatable: false,
    },
    {
      id: "auto_avg_balls_cycle",
      label: "Avg Auto Balls Per Cycle",
      type: "counter",
      section: "auto",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: true,
      increment: 5,
    },
    {
      id: "auto_shoot_cycles",
      label: "Auto Shoot Cycles",
      type: "counter",
      section: "auto",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "auto_notes",
      label: "Auto Notes",
      type: "text",
      section: "auto",
      aggregatable: false,
    },

    // ── TELEOP ────────────────────────────────────────────────────────────────
    {
      id: "tele_avg_balls_shot",
      label: "Avg Balls Per Shooting Cycle",
      type: "counter",
      section: "teleop",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: true,
      increment: 5,
    },
    {
      id: "tele_shoot_cycles",
      label: "Shooting Cycles",
      type: "counter",
      section: "teleop",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "tele_shoot_moving",
      label: "Shoots on Move",
      type: "boolean",
      section: "teleop",
      defaultValue: false,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "tele_shoot_accuracy",
      label: "Shooting Accuracy",
      type: "rating",
      section: "teleop",
      defaultValue: 3,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "tele_avg_balls_fed",
      label: "Avg Balls Per Feed Cycle",
      type: "counter",
      section: "teleop",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: true,
      increment: 5,
    },
    {
      id: "tele_feed_cycles",
      label: "Feeding Cycles",
      type: "counter",
      section: "teleop",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: false,
    },
    {
      id: "tele_defense",
      label: "Played Defense",
      type: "boolean",
      section: "teleop",
      defaultValue: false,
      aggregatable: true,
      higherIsBetter: false,
    },
    {
      id: "tele_defense_quality",
      label: "Defense Quality",
      type: "rating",
      section: "teleop",
      defaultValue: 3,
      aggregatable: true,
      higherIsBetter: true,
      conditionalOnField: "tele_defense",
    },
    {
      id: "tele_was_defended",
      label: "Was Defended",
      type: "boolean",
      section: "teleop",
      defaultValue: false,
      aggregatable: false,
    },
    {
      id: "tele_defense_handling",
      label: "Handled Defense",
      type: "rating",
      section: "teleop",
      defaultValue: 3,
      aggregatable: true,
      higherIsBetter: true,
      conditionalOnField: "tele_was_defended",
    },
    {
      id: "tele_defense_notes",
      label: "Defense Notes",
      type: "text",
      section: "teleop",
      aggregatable: false,
    },

    // ── ENDGAME ───────────────────────────────────────────────────────────────
    {
      id: "end_climb",
      label: "Climb Result",
      type: "select",
      options: ["None", "L1", "L2", "L3"],
      section: "endgame",
      defaultValue: "None",
      aggregatable: true,
      higherIsBetter: true,
    },

    // ── NOTES ─────────────────────────────────────────────────────────────────
    {
      id: "notes_driver_skill",
      label: "Driver Skill",
      type: "rating",
      section: "notes",
      defaultValue: 3,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "notes_driver_notes",
      label: "Driver Notes",
      type: "text",
      section: "notes",
      aggregatable: false,
    },
    {
      id: "notes_feed_quality",
      label: "Bulldoze/Feed Quality",
      type: "rating",
      section: "notes",
      defaultValue: 3,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "notes_speed",
      label: "Robot Speed",
      type: "rating",
      section: "notes",
      defaultValue: 3,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "notes_would_pick",
      label: "Would Pick",
      type: "select",
      options: ["Yes", "Maybe", "No"],
      section: "notes",
      aggregatable: false,
    },
    {
      id: "notes_general",
      label: "Match Notes",
      type: "text",
      section: "notes",
      aggregatable: false,
    },
  ],

  pitFields: [
    // ── GENERAL ───────────────────────────────────────────────────────────────
    {
      id: "pit_weight",
      label: "Robot Weight (lbs)",
      type: "number",
      section: "general",
      aggregatable: false,
    },
    {
      id: "pit_height",
      label: "Robot Height (in)",
      type: "number",
      section: "general",
      aggregatable: false,
    },

    // ── DRIVETRAIN ────────────────────────────────────────────────────────────
    {
      id: "pit_drivetrain",
      label: "Drivetrain Type",
      type: "select",
      options: ["Swerve", "Tank", "Mecanum", "Omni", "Other"],
      section: "drivetrain",
      defaultValue: "Swerve",
      aggregatable: true,
    },
    {
      id: "pit_drive_motors",
      label: "Drive Motors",
      type: "select",
      options: ["Kraken X60", "Falcon 500", "NEO", "NEO Vortex", "CIM", "Other"],
      section: "drivetrain",
      aggregatable: false,
    },

    // ── SHOOTER ───────────────────────────────────────────────────────────────
    {
      id: "pit_hopper_size",
      label: "Hopper Capacity (balls)",
      type: "number",
      section: "shooter",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "pit_shooter_type",
      label: "Shooter Type",
      type: "select",
      options: ["Single", "Double", "Triple", "Drum", "Single Turret", "Double Turret", "None"],
      section: "shooter",
      aggregatable: false,
    },
    {
      id: "pit_shoot_range",
      label: "Effective Shooting Range",
      type: "select",
      options: ["Close Only", "Mid Range", "Long Range", "Full Field", "All Ranges"],
      section: "shooter",
      aggregatable: false,
    },
    {
      id: "pit_can_feed",
      label: "Can Feed/Pass to Allies",
      type: "boolean",
      section: "shooter",
      defaultValue: false,
      aggregatable: true,
      higherIsBetter: true,
    },

    // ── AUTO ──────────────────────────────────────────────────────────────────
    {
      id: "pit_auto_modes",
      label: "Number of Auto Modes",
      type: "counter",
      section: "auto",
      defaultValue: 0,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "pit_auto_reliable",
      label: "Auto Reliability",
      type: "rating",
      section: "auto",
      defaultValue: 3,
      aggregatable: true,
      higherIsBetter: true,
    },

    // ── ENDGAME ───────────────────────────────────────────────────────────────
    {
      id: "pit_can_climb",
      label: "Can Climb",
      type: "boolean",
      section: "endgame",
      defaultValue: false,
      aggregatable: true,
      higherIsBetter: true,
    },
    {
      id: "pit_climb_max",
      label: "Max Climb Level",
      type: "select",
      options: ["None", "L1", "L2", "L3"],
      section: "endgame",
      defaultValue: "None",
      aggregatable: true,
    },

    // ── NOTES ─────────────────────────────────────────────────────────────────
    {
      id: "pit_notes",
      label: "General Notes",
      type: "text",
      section: "notes",
      aggregatable: false,
    },
  ],
};
